variables:
  IMAGE_VERSION: $NNP_COMP_IMG_VERSION
  APP_NAME: $CI_PROJECT_NAME
  APP_LABEL: $CI_PROJECT_NAME
  REPLICAS: 1
  IMAGE: "${CI_REGISTRY_IMAGE}:${IMAGE_VERSION}"
  PORT: 8000
  SERVICE_PORT: 8000
  NAMESPACE: "nnp-core-components"
  SERVICE_TYPE: "NodePort"
  REQUEST_MEMORY: "1000Mi"
  REQUEST_CPU: "600m"
  LIMIT_MEMORY: "2000Mi"
  LIMIT_CPU: "1000m"
  
  
  

stages: 

  - publish
  - test
  - deploy
  - post-deploy

include:


  - project: "devops-templates/build-templates"
    ref: "main"
    file: "container-build-template.yml"

  - project: "devops-templates/security-templates"
    ref: "main"
    file: "container-image-scan-template.yml"
    
  - project: "devops-templates/deploy-templates"
    ref: "main"
    file: "k8s-deployment-template.yaml"  
  
